export const team = [
  {
    id: "hasib",
    name: "Mohammad Hasib",
    role: "Founder & Full Stack Developer",
    bio: "Full-stack developer and tech lead with deep expertise in modern web architecture. Builds scalable products from concept to deployment.",
    skills: ["Next.js", "React", "Node.js", "MongoDB", "AI"],
    experience: "5+ Years · Full Stack",
    image: "/images/team/hasib.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "business-research",
    name: "Tasfik Bin Osman",
    role: "Business Research Analyst",
    bio: "Data-driven researcher specializing in market analysis and consumer insights. Passionate about turning data into actionable strategies.",
    skills: ["Research", "Analysis", "Strategy", "Communication"],
    experience: "1+ Years · Research",
    image: "/images/team/tasfik.png",
    linkedin: "#",
    portfolio: "https://tasfik-portfolio.vercel.app/",
  },
  {
    id: "sales",
    name: "Sadia Rahman",
    role: "Sales Executive",
    bio: "Client relationship expert who matches businesses with the perfect digital solutions. Drives growth through strategic communication.",
    skills: ["CRM", "Communication", "Strategy", "Negotiation"],
    experience: "4+ Years · Business Dev",
    image: "/images/team/sales.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "content",
    name: "Nusrat Jahan",
    role: "Content Manager",
    bio: "Brand storyteller crafting compelling narratives across social media, websites, and marketing campaigns that resonate with audiences.",
    skills: ["Branding", "SEO", "Social Media", "Research"],
    experience: "3+ Years · Marketing",
    image: "/images/team/content.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "growth",
    name: "Rafsan Karim",
    role: "Growth Manager",
    bio: "Growth strategist managing online presence, ad campaigns, and community engagement to expand digital footprint and brand reach.",
    skills: ["Ads", "Analytics", "Growth", "Community"],
    experience: "3+ Years · Growth",
    image: "/images/team/growth.jpg",
    linkedin: "#",
    portfolio: "#",
  },
]
