export const team = [
  {
    id: "hasib",
    name: "Mohammad Hasib",
    role: "Founder & Full Stack Developer",
    bio: "Full-stack developer and tech lead with deep expertise in modern web architecture. Builds scalable products from concept to deployment.",
    skills: ["Next.js", "React", "Node.js", "MongoDB", "AI"],
    experience: "5+ Years · Full Stack",
    image: "/images/team/hasib.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "frontend-dev",
    name: "Tanvir Ahmed",
    role: "Frontend Developer",
    bio: "UI specialist crafting pixel-perfect interfaces with modern frameworks. Obsessed with responsive design and smooth animations.",
    skills: ["React", "Tailwind", "TypeScript", "Motion"],
    experience: "3+ Years · Frontend",
    image: "/images/team/frontend-dev.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "sales",
    name: "Sadia Rahman",
    role: "Sales Executive",
    bio: "Client relationship expert who matches businesses with the perfect digital solutions. Drives growth through strategic communication.",
    skills: ["CRM", "Communication", "Strategy", "Negotiation"],
    experience: "4+ Years · Business Dev",
    image: "/images/team/sales.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "content",
    name: "Nusrat Jahan",
    role: "Content Manager",
    bio: "Brand storyteller crafting compelling narratives across social media, websites, and marketing campaigns that resonate with audiences.",
    skills: ["Branding", "SEO", "Social Media", "Research"],
    experience: "3+ Years · Marketing",
    image: "/images/team/content.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "growth",
    name: "Rafsan Karim",
    role: "Growth Manager",
    bio: "Growth strategist managing online presence, ad campaigns, and community engagement to expand digital footprint and brand reach.",
    skills: ["Ads", "Analytics", "Growth", "Community"],
    experience: "3+ Years · Growth",
    image: "/images/team/growth.jpg",
    linkedin: "#",
    portfolio: "#",
  },
]
