export const team = [
  {
    id: "hasib",
    name: "Mohammad Hasib",
    role: "Founder & Full Stack Developer",
    bio: "Full-stack developer and tech lead with deep expertise in modern web architecture. Builds scalable products from concept to deployment.",
    skills: ["Next.js", "React", "Node.js", "MongoDB", "AI"],
    experience: "2+ Years · Full Stack",
    image: "/images/team/hasib.jpg",
    linkedin: "https://www.linkedin.com/in/codehasib/",
    portfolio: "https://codehasib-portfolio.vercel.app/",
  },
  {
    id: "business-research",
    name: "Tasfik Bin Osman",
    role: "Business Research Analyst",
    bio: "Data-driven researcher specializing in market analysis and consumer insights. Passionate about turning data into actionable strategies.",
    skills: ["Research", "Analysis", "Strategy", "Communication"],
    experience: "1+ Years · Research",
    image: "/images/team/tasfik.jpg",
    linkedin: "#",
    portfolio: "https://tasfik-portfolio.vercel.app/",
  },
  {
    id: "salesTwo",
    name: "Fariha Reza Nitu",
    role: "Sales Executive",
    bio: "Client relationship expert who matches businesses with the perfect digital solutions. Drives growth through strategic communication.",
    skills: ["CRM", "Communication", "Strategy", "Negotiation"],
    experience: "1+ Years · Business Dev",
    image: "/images/team/nitu1.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "sales",
    name: "Zidan Joshpe Gomes",
    role: "Sales Executive",
    bio: "Client relationship expert who matches businesses with the perfect digital solutions. Drives growth through strategic communication.",
    skills: ["CRM", "Communication", "Strategy", "Negotiation"],
    experience: "1+ Years · Business Dev",
    image: "/images/team/zidan.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "ui-ux-designer",
    name: "Maisha Hossain Farabi",
    role: "UI/UX Designer",
    bio: "User-centered designer who crafts intuitive, visually engaging digital experiences. Drives product success through strategic wire-framing, prototyping, and user research.",
    skills: [
      "Figma",
      "User Research",
      "Wireframing",
      "Prototyping",
      "UI Design",
    ],
    experience: "1+ Years · Digital Product Design",
    image: "/images/team/farabi.png",
    linkedin: "#",
    portfolio: "https://farabi-portfolio-mocha.vercel.app/",
  },
  {
    id: "content",
    name: "Ami Acharya",
    role: "Content Manager",
    bio: "Brand storyteller crafting compelling narratives across social media, websites, and marketing campaigns that resonate with audiences.",
    skills: ["Branding", "SEO", "Social Media", "Research"],
    experience: "1+ Years · Content Creation",
    image: "/images/team/ami.jpg",
    linkedin: "#",
    portfolio: "#",
  },
  {
    id: "growth",
    name: "Salnam Nengminja",
    role: "Digital Marketing Manager",
    bio: "Growth strategist managing online presence, ad campaigns, and community engagement to expand digital footprint and brand reach.",
    skills: ["Ads", "Analytics", "Growth", "Community"],
    experience: "1+ Years · Growth",
    image: "/images/team/salnam.jpg",
    linkedin: "#",
    portfolio: "https://salnam-portfolio.vercel.app/",
  },
];
