export const plans = [
  {
    id: "starter",
    name: "Starter Website",
    tagline: "Perfect for small businesses",
    price: "৳5,000",
    priceLabel: "Starting from",
    cta: "Start Project",
    popular: false,
    accent: "from-accent to-accent-secondary",
    features: [
      "Responsive Website",
      "Contact Form",
      "WhatsApp Button",
      "Google Maps",
      "Basic SEO",
      "Delivery 3–5 Days",
    ],
  },
  {
    id: "business-site",
    name: "Business Website",
    tagline: "For growing brands",
    price: "৳15,000",
    priceLabel: "Starting from",
    cta: "Start Project",
    popular: true,
    accent: "from-accent-secondary to-accent",
    features: [
      "Custom Design",
      "CMS Ready",
      "Blog",
      "Analytics",
      "Speed Optimization",
      "Advanced SEO",
      "Admin Panel (optional)",
    ],
  },
  {
    id: "business-software",
    name: "Business Software",
    tagline: "End-to-end solutions",
    price: "৳40,000",
    priceLabel: "Starting from",
    cta: "Start Project",
    popular: false,
    accent: "from-accent to-accent-secondary",
    features: [
      "Inventory",
      "CRM",
      "POS",
      "Dashboard",
      "Reports",
      "User Management",
      "Authentication",
    ],
  },
  {
    id: "custom",
    name: "Custom Solution",
    tagline: "Let's Build Your Idea",
    price: "Custom Quote",
    priceLabel: "",
    cta: "Book Strategy Call",
    popular: false,
    accent: "from-accent-secondary to-accent",
    features: [
      "SaaS",
      "AI",
      "Marketplace",
      "Mobile App",
      "Automation",
      "API",
      "Cloud Deployment",
    ],
  },
]

export const featureCompare = [
  { feature: "Responsive", starter: true, business: true, software: true, custom: true },
  { feature: "Custom Design", starter: false, business: true, software: true, custom: true },
  { feature: "Admin Dashboard", starter: false, business: "optional", software: true, custom: true },
  { feature: "CMS", starter: false, business: true, software: false, custom: true },
  { feature: "SEO", starter: "basic", business: "advanced", software: false, custom: true },
  { feature: "Analytics", starter: false, business: true, software: true, custom: true },
  { feature: "Hosting Support", starter: false, business: true, software: true, custom: true },
  { feature: "Maintenance", starter: false, business: false, software: true, custom: true },
  { feature: "API", starter: false, business: false, software: false, custom: true },
  { feature: "Authentication", starter: false, business: false, software: true, custom: true },
  { feature: "Mobile Friendly", starter: true, business: true, software: true, custom: true },
]

export const trustStats = [
  { value: 50, suffix: "+", label: "Projects" },
  { value: 98, suffix: "%", label: "Client Satisfaction" },
  { value: 24, suffix: "/7", label: "Support" },
  { value: 100, suffix: "%", label: "Responsive" },
]
