import {
  Globe,
  Monitor,
  ShoppingCart,
  UtensilsCrossed,
  Package,
  GraduationCap,
  Stethoscope,
  Building2,
  Users,
  CalendarCheck,
  Bot,
  Megaphone,
  Server,
  Wrench,
  Mail,
  BarChart3,
} from "lucide-react"

export const ecosystemNodes = [
  {
    id: "business-website",
    label: "Business Website",
    icon: Globe,
    headline: "Professional websites built to convert visitors into customers.",
    description:
      "We create modern, responsive websites optimized for branding, trust, speed, and SEO — giving your business a powerful online presence that drives results.",
    deliverables: [
      "Responsive Website",
      "SEO Setup",
      "Contact Forms",
      "WhatsApp Integration",
      "Google Maps",
      "CMS",
    ],
    timeline: "5–10 Days",
    startingPrice: "From 5K BDT",
    recommendedFor: "New businesses, startups, and companies needing a modern web presence.",
  },
  {
    id: "landing-page",
    label: "Landing Page",
    icon: Monitor,
    headline: "High-conversion landing pages built for campaigns and launches.",
    description:
      "Purpose-built single-page experiences designed to capture leads, promote offers, and drive specific actions with clear messaging and strong CTAs.",
    deliverables: [
      "Single Page Design",
      "Lead Capture Form",
      "CTA Optimization",
      "Analytics Setup",
      "A/B Testing Ready",
      "Fast Load Times",
    ],
    timeline: "2–4 Days",
    startingPrice: "From 2K BDT",
    recommendedFor: "Product launches, promotions, ad campaigns, and event registration.",
  },
  {
    id: "ecommerce",
    label: "E-Commerce",
    icon: ShoppingCart,
    headline: "Full-featured online stores that sell around the clock.",
    description:
      "End-to-end e-commerce solutions with product management, secure payments, inventory sync, and marketing automation built for growth.",
    deliverables: [
      "Product Catalog",
      "Payment Gateway",
      "Cart & Checkout",
      "Order Management",
      "Inventory Sync",
      "Customer Accounts",
    ],
    timeline: "10–20 Days",
    startingPrice: "From 15K BDT",
    recommendedFor: "Retailers, brands, and wholesalers moving online or scaling operations.",
  },
  {
    id: "restaurant-pos",
    label: "Restaurant POS",
    icon: UtensilsCrossed,
    headline: "Complete restaurant management with POS and online ordering.",
    description:
      "A unified system connecting your restaurant's front-of-house, kitchen, online orders, and delivery channels into one seamless operation.",
    deliverables: [
      "POS System",
      "QR Menu",
      "Online Ordering",
      "Kitchen Display",
      "Delivery Integration",
      "Sales Reports",
    ],
    timeline: "7–14 Days",
    startingPrice: "From 10K BDT",
    recommendedFor: "Restaurants, cafes, cloud kitchens, and food chains.",
  },
  {
    id: "inventory",
    label: "Inventory Software",
    icon: Package,
    headline: "Real-time inventory tracking across all your locations.",
    description:
      "Powerful inventory management with barcode scanning, multi-warehouse support, low-stock alerts, and detailed reporting to keep your supply chain running smoothly.",
    deliverables: [
      "Stock Tracking",
      "Barcode Scanning",
      "Multi-Warehouse",
      "Low Stock Alerts",
      "Purchase Orders",
      "Sales Analytics",
    ],
    timeline: "7–14 Days",
    startingPrice: "From 12K BDT",
    recommendedFor: "Wholesalers, retailers, manufacturers, and distribution businesses.",
  },
  {
    id: "school-management",
    label: "School Management",
    icon: GraduationCap,
    headline: "Digital platform for managing students, staff, and academics.",
    description:
      "A comprehensive school management system handling admissions, attendance, grades, timetables, fees, and parent communication from a single dashboard.",
    deliverables: [
      "Student Database",
      "Attendance System",
      "Grade Management",
      "Fee Collection",
      "Timetable Planner",
      "Parent Portal",
    ],
    timeline: "10–20 Days",
    startingPrice: "From 20K BDT",
    recommendedFor: "Schools, colleges, coaching centers, and educational institutions.",
  },
  {
    id: "hospital-management",
    label: "Hospital Management",
    icon: Stethoscope,
    headline: "Healthcare platform for patient management and operations.",
    description:
      "A complete hospital management system covering appointments, electronic health records, billing, pharmacy, and lab management in one secure platform.",
    deliverables: [
      "Patient Records",
      "Appointment Booking",
      "EHR System",
      "Billing & Insurance",
      "Pharmacy Management",
      "Lab Integration",
    ],
    timeline: "15–30 Days",
    startingPrice: "From 30K BDT",
    recommendedFor: "Hospitals, clinics, diagnostic centers, and healthcare networks.",
  },
  {
    id: "custom-erp",
    label: "Custom ERP",
    icon: Building2,
    headline: "Tailored enterprise software for your unique workflows.",
    description:
      "Bespoke ERP systems connecting finance, HR, operations, sales, and supply chain into a single unified platform designed around your specific business processes.",
    deliverables: [
      "Requirements Analysis",
      "Custom Modules",
      "Dashboard & Reports",
      "User Roles & Permissions",
      "Third-Party Integration",
      "Training & Support",
    ],
    timeline: "30–60 Days",
    startingPrice: "From 50K BDT",
    recommendedFor: "Growing enterprises with complex workflows needing custom solutions.",
  },
  {
    id: "crm",
    label: "CRM",
    icon: Users,
    headline: "Customer relationship management built for sales teams.",
    description:
      "A powerful CRM system to track leads, manage contacts, automate follow-ups, and close more deals with data-driven sales intelligence.",
    deliverables: [
      "Contact Management",
      "Lead Tracking",
      "Pipeline Management",
      "Email Integration",
      "Task Automation",
      "Sales Analytics",
    ],
    timeline: "7–14 Days",
    startingPrice: "From 10K BDT",
    recommendedFor: "Sales teams, real estate agencies, and service-based businesses.",
  },
  {
    id: "booking-platform",
    label: "Booking Platform",
    icon: CalendarCheck,
    headline: "Online booking and reservation system for your service.",
    description:
      "A seamless booking platform enabling customers to schedule appointments, make reservations, and pay online — reducing no-shows and admin workload.",
    deliverables: [
      "Online Booking",
      "Calendar Sync",
      "Payment Collection",
      "Automated Reminders",
      "Staff Management",
      "Availability Dashboard",
    ],
    timeline: "5–10 Days",
    startingPrice: "From 8K BDT",
    recommendedFor: "Salons, clinics, gyms, consultants, and service professionals.",
  },
  {
    id: "ai-chatbot",
    label: "AI Chatbot",
    icon: Bot,
    headline: "Intelligent chatbots that automate customer conversations.",
    description:
      "AI-powered chatbots that handle inquiries, qualify leads, process orders, and provide 24/7 customer support using natural language processing.",
    deliverables: [
      "Conversation Design",
      "FAQ Automation",
      "Lead Qualification",
      "Multi-Platform Deployment",
      "Analytics Dashboard",
      "Human Handoff",
    ],
    timeline: "5–10 Days",
    startingPrice: "From 8K BDT",
    recommendedFor: "E-commerce stores, service businesses, and high-volume customer support.",
  },
  {
    id: "marketing-automation",
    label: "Marketing Automation",
    icon: Megaphone,
    headline: "Automated marketing campaigns that nurture and convert.",
    description:
      "Multi-channel marketing automation covering email, SMS, social media, and retargeting — designed to engage customers at every stage of the funnel.",
    deliverables: [
      "Email Campaigns",
      "SMS Marketing",
      "Social Media Scheduling",
      "Lead Nurturing Flows",
      "Audience Segmentation",
      "Performance Reports",
    ],
    timeline: "5–10 Days",
    startingPrice: "From 8K BDT",
    recommendedFor: "Businesses running regular marketing campaigns and email outreach.",
  },
  {
    id: "hosting",
    label: "Hosting",
    icon: Server,
    headline: "Fast, secure, and reliable hosting for your digital products.",
    description:
      "Premium hosting infrastructure with SSD storage, CDN, daily backups, SSL certificates, and 99.9% uptime guarantee for all your websites and applications.",
    deliverables: [
      "SSD Hosting",
      "SSL Certificate",
      "Daily Backups",
      "CDN Integration",
      "99.9% Uptime",
      "24/7 Monitoring",
    ],
    timeline: "1 Day",
    startingPrice: "From 500 BDT/mo",
    recommendedFor: "Any business with websites, apps, or online platforms.",
  },
  {
    id: "maintenance",
    label: "Maintenance",
    icon: Wrench,
    headline: "Ongoing support and maintenance to keep everything running.",
    description:
      "Proactive maintenance covering updates, security patches, performance optimization, bug fixes, and content updates to keep your digital products in top shape.",
    deliverables: [
      "Regular Updates",
      "Security Patches",
      "Performance Tuning",
      "Bug Fixes",
      "Content Updates",
      "Monthly Reports",
    ],
    timeline: "Ongoing",
    startingPrice: "From 2K BDT/mo",
    recommendedFor: "Businesses wanting worry-free operation of their digital products.",
  },
  {
    id: "brand-identity",
    label: "Brand Identity",
    icon: Megaphone,
    headline: "Complete brand identity design that sets you apart.",
    description:
      "Strategic brand development including logo design, color palette, typography, brand guidelines, and visual assets that communicate your unique value proposition.",
    deliverables: [
      "Logo Design",
      "Color Palette",
      "Typography System",
      "Brand Guidelines",
      "Business Cards",
      "Social Media Kit",
    ],
    timeline: "5–10 Days",
    startingPrice: "From 5K BDT",
    recommendedFor: "New businesses and brands undergoing a visual refresh.",
  },
  {
    id: "analytics",
    label: "Analytics",
    icon: BarChart3,
    headline: "Data analytics dashboards for informed decision-making.",
    description:
      "Custom analytics platforms that aggregate data from multiple sources into beautiful, interactive dashboards — giving you real-time visibility into your business performance.",
    deliverables: [
      "Data Integration",
      "Custom Dashboard",
      "Real-Time Reports",
      "KPI Tracking",
      "Export & Sharing",
      "Alert System",
    ],
    timeline: "7–14 Days",
    startingPrice: "From 10K BDT",
    recommendedFor: "Data-driven businesses needing actionable insights at a glance.",
  },
]
